### ISSUE TITLE
Logging support

### ISSUE THREAD

**Issue by mperham** [contribsys/faktory_worker_go#1]
Integrate Go's logging best practices.  We probably shouldn't be using `faktory/util`'s logging API but rather allow the app developer to give us a logging instance to use.

**Comment by JeanMertz** [comment]
Support for [zap](https://github.com/uber-go/zap) would be nice to have 👍

**Comment by mperham** [comment]
Love it, thanks for the pointer.

**Comment by mperham** [comment]
Removed faktory/util, now using the standard log package which can be overridden.
