### ISSUE TITLE
How to add labels for the UI

### ISSUE THREAD

**Issue by CaryLandholt** [contribsys/faktory_worker_go#17]
I would like to pass an array of Labels to be displayed in the UI, like `golang` is currently.
https://github.com/contribsys/faktory/blob/50e383d42aede70c4fd8645c636f5295e55be988/client/client.go#L375

Any ideas how to do this when configuring the manager?

**Comment by mperham** [comment]
Right now there's no way to configure the client data before it connects to Faktory so you only see the defaults.  I'd welcome any API improvements here.  Maybe golang's TLS package would be a good reference for how to provide a configurable client API.

**Comment by besser** [comment]
I made a pull request about this issue: https://github.com/contribsys/faktory_worker_go/pull/32
