### ISSUE TITLE
Queues from worker.NewManager() is no longer exported, causing a breaking change

### ISSUE THREAD

**Issue by CaryLandholt** [contribsys/faktory_worker_go#21]
`Queues` was being exported, but was renamed to `queues` causing apps to break.
https://github.com/contribsys/faktory_worker_go/blob/master/runner.go#L42

Is the intent to use `ProcessStrictPriorityQueues` and/or `ProcessWeightedPriorityQueues` in lieu of `Queues`?

**Comment by mperham** [comment]
Yes, readme was adjusted to show the new api.

**Comment by mperham** [comment]
Until 1.0 the API can fluctuate.  I have a Version variable but I need to implement version tagging in the repo.
