### ISSUE TITLE
Worker/Manager per process

### ISSUE THREAD

**Issue by APengue1** [contribsys/faktory_worker_go#23]
I'm having an issue running one worker per process.
Everything is local and I have a faktory server running on :7419.

I have a workflow consisting of AMQP message queues and Faktory jobs. AMQP messages are consumed and packaged into a faktory job, which then produces output on another message queue.

I have it set up such that each job produce/worker is run in its own process, with AMQP message queues and Faktory jobs as a means of communication.

If only one worker process for JOB_A is running, it receives jobs instantaneously. If however I run my JOB_B worker process, they both receive jobs intermittently. Looking at the retry queue, I see that the jobs not processed have an error message: `unknown: No handler for JOB_A`. I would say around 30-50% of jobs need to be retried, and eventually they process successfully within 5 retries. As soon as I turn off JOB_B, everything is back to normal.

In each process for JOB_A and JOB_B, because they are different processes, the following is run for each process:
``` go
mgr := faktory_worker_go.NewManager()
mgr.Register("JOB_*", fn)
mgr.Run()
```

If however I refactor my workers to run in a single process, calling Register twice and Run once, everything runs very smoothly:
``` go
mgr := faktory_worker_go.NewManager()
mgr.Register("JOB_A", fn_A)
mgr.Register("JOB_B", fn_B)
mgr.Run()
```

Is it not intended to run one worker per process?
I would really prefer to logically separate independent jobs/workers into new processes.

**Comment by mperham** [comment]
You target different processes to different **queues**.  Put the jobs on different queues.

Where did you get the idea that wildcards would work?  This will do nothing: `mgr.Register("JOB_*", fn)`

**Comment by APengue1** [comment]
I will explore the queues approach, thank you.
The wild card is not literal. I was implying running that block of code twice, with the wildcard being either A or B depending on the process.

**Comment by APengue1** [comment]
The queue approach worked very well, thank you.
I set the queue name to be the job name, eg: JOB_A.
Is there a particular standard or pattern I should adhere to?

**Comment by mperham** [comment]
Name your queues logically, according to how they are split.  For instance, you might have a `warehouse` queue and an `email` queue.  Or you can name your queues according to priority so that certain jobs are handled first, e.g. `critical`, `default`, `low`.
