### ISSUE TITLE
[QUESTION] Do I need run someFunc in go route manually?

### ISSUE THREAD

**Issue by aetherwu** [contribsys/faktory_worker_go#29]
Sorry to ask this question, but as a newbie just want to make sure I can implement the worker funcs properly.

Questions:
1. Do I need run someFunc in go route manually? Or it is handled by faktory automatically in aync go route.
2. Is "go route" (as it was written in test) to produce() necessary or optional, or is it better/suggested to add any task in go-route?
3. Do these funcs necessary to init the mgr or it is optional by default setting?
```
mgr.Concurrency = 20
mgr.ProcessStrictPriorityQueues("critical", "default", "bulk")
```

Thank you for your time and patience.

**Comment by mperham** [comment]
1. I don't understand.
2. I don't understand.
3. The defaults are in the code here: https://github.com/contribsys/faktory_worker_go/blob/master/runner.go#L89
