### ISSUE TITLE
Testing/Mocking

### ISSUE THREAD

**Issue by nikoma** [contribsys/faktory_worker_go#30]
Is there a best practice as to how to mock faktory for testing?

**Comment by mperham** [comment]
Nope. I've given it zero thought.

**Comment by paulrostorp** [comment]
I would like to write some tests as well. is there Any way to generate a dummy context ?

**Comment by mperham** [comment]
You'll need to be more specific.  Are you talking about `context.Background()`?

**Comment by paulrostorp** [comment]
worker.Context, the first parameter defined in the functions

**Comment by mperham** [comment]
https://github.com/contribsys/faktory_worker_go/blob/master/runner.go#L300
