### ISSUE TITLE
version tag

### ISSUE THREAD

**Issue by jdupl123** [contribsys/faktory_worker_go#31]
Because there is no version tag go mod takes the last commit from master. 

This caused our ci pipeline to break with the following error

/root/go/src/github.com/contribsys/faktory_worker_go/runner.go:289:9: undefined: client.Batch

After commit: f4d3451cb3b183e2acd6c2ff559477d6bdc4e5c8

Would it make sense to create version tags?

If anyone else has this issue you can put `github.com/contribsys/faktory_worker_go v0.0.0-20191008193933-9f13abade33b` in go.mod to get the stable version.

**Comment by mperham** [comment]
Sorry, I've both fixed that commit and introduced a v0.8.0 tag for the
previously stable code, before the recent work.

**Comment by jdupl123** [comment]
Great thanks.
