### ISSUE TITLE
Enqueued Jobs are Stuck

### ISSUE THREAD

**Issue by profsmallpine** [contribsys/faktory_worker_go#33]
About a week ago, I noticed that the enqueued jobs was growing.

![Screen Shot 2020-02-10 at 3 24 49 PM](https://user-images.githubusercontent.com/7328006/74195933-85266200-4c19-11ea-826c-4f30a82f984e.png)

I tried updating from faktory 1..1.0-1 to 1.2.0-1. I also updated faktory_worker_go to the latest release. This did not solve the problem. On some of my jobs, they might kick off another job right before they return. I've noticed that the kick-off job does not get removed from the queue while the new job gets added. The worker is still running, though it is not picking up new jobs, nor does it seem to tell faktory that it is done with existing jobs. The worker is running and has no logs. My worker is configured as so:

```
// Run faktory worker server and register jobs
mgr := worker.NewManager()
// faktory.RegisterJobs(mgr, procedures) - application code which calls mgr.Register for each known job
mgr.ProcessStrictPriorityQueues(faktory.Critical, faktory.Default, faktory.Bulk)
mgr.Run()
```

Please let me know how else I can help debug.

**Comment by mperham** [comment]
I've added support for dumping all thread stacktraces in fwg v1.0.1.  If you upgrade and send the TTIN signal, fwg will print out the stack for all goroutines in the process, which should give you a powerful tool to track down "stuck" worker processes.

**Comment by profsmallpine** [comment]
Thanks for adding this! After fixing the issue over here: https://github.com/contribsys/faktory/issues/286, I haven't see this specific issue again. I don't know if there is some odd case where the panic happens in the thread when attempting to add a background job, and it gets lost in a loop or something so the service is no longer working, but it takes some time for it to show as dead. No matter what, I don't think the issue is in faktory_worker_go. Wanted to follow up and close this out. Happy friday.
