### ISSUE TITLE
Stopping Busy Jobs

### ISSUE THREAD

**Issue by adrianotadao** [contribsys/faktory_worker_go#34]
Hello all, is there a way of stopping a busy Job?

<img width="1214" alt="Screen Shot 2020-02-26 at 12 20 44" src="https://user-images.githubusercontent.com/387138/75359010-7f27b680-5892-11ea-91e4-16a593a97e43.png">

I don't want to run this job anymore so, I stopped the server and everything but it always tries to run when I start the server again.

thank you very much!

**Comment by mperham** [comment]
faktory_worker_go supplies a Context for job execution which allows you to set a Deadline or cancel the job internally. There is no way to stop a running job externally. Once a job enters the retry queue, you can Kill it in the UI so that it doesn't re-execute.

**Comment by adrianotadao** [comment]
Thanks @mperham
