### ISSUE TITLE
Release error: too many arguments in call to c.Beat

### ISSUE THREAD

**Issue by adrianotadao** [contribsys/faktory_worker_go#35]
Hello @mperham, I'm using your lib but the released version has a bug.

```
➜ go get -u github.com/contribsys/faktory_worker_go
# github.com/contribsys/faktory_worker_go
../../golang/pkg/mod/github.com/contribsys/faktory_worker_go@v1.0.1/runner.go:190:24: too many arguments in call to c.Beat
	have (string)
	want ()
```

The `runner.go` calls `client.Beat()` and sends the current state `mgr.CurrentState()`
https://github.com/contribsys/faktory_worker_go/blob/17dd45681297754771d8d61c6e8b64231aebfd1c/runner.go#L189-L190

This version requires `faktory v1.2.0-1 `

https://github.com/contribsys/faktory_worker_go/blob/17dd45681297754771d8d61c6e8b64231aebfd1c/go.mod#L5-L8

Which doesn't have a `Beat()` method that receives any argument.

https://github.com/contribsys/faktory/blob/5a6c200269abb81a8f718c9995742d847f042a5f/client/client.go#L431-L437

Would be possible to release a brand new version to get it fixed? I was using the master branch in development but I don't want to do the same for production.

Thank you very much!

**Comment by mperham** [comment]
You're right, I think you'll need to use v1.0.0 until I can release Faktory v1.3.0 and fwg 1.1.0.

**Comment by adrianotadao** [comment]
@mperham `v1.0.0` works well. Thank you Mike

**Comment by mperham** [comment]
Faktory and fwg v1.3.0-1 have been released, let me know if you upgrade and still see issues.

**Comment by adrianotadao** [comment]
@mperham It worked well. Thank you again!
