### ISSUE TITLE
Need context access to set and get the context

### ISSUE THREAD

**Issue by kumarsiva07** [contribsys/faktory_worker_go#36]
I used https://github.com/gocraft/work before this. In that, I can create my own Context and can use it in middleware and inside the worker func. 

In faktory, I can get the value from the context from the interface. But I could not set the value to the context. 

![image](https://user-images.githubusercontent.com/7725174/75602828-9ebb1b00-5aee-11ea-8e8d-e11b93922a5e.png)

Can you help me to set context values? 
like SetValue("log_map", map[string]interface{}{"app": "demo app", "user_id": 12})

Because our logs print current user related values in all logs using the context.

**Comment by mperham** [comment]
fwg provides a worker.Context with each job while executing, you do not create the context. You can access extra custom fields (like the customer ID associated with the job) in job.Custom, see job.GetCustom(). You can also use the full context API in the context package.

If you can be more precise about what you are trying to do, I'll be glad to help more.

**Comment by kumarsiva07** [comment]
I tried job.GetCustom(). But I will brief my use case.

We have two packages. One for DB connection wrapper and the other one is logs wrapper.
In DB wrapper, We are getting the account_id and user_id from context API. We will set the account_id and user_id in the middleware on the web and the faktory.  After that for each query to DB, we wil use that context the set the default condition 

> ` account_id=? AND iuser_id =?, ctx.Value("account_id").(uint64),  ctx.Value("user_d").(uint64), `.

In logs wrapper, We will pass ctx and the string to _mlog.Print(ctx, "test log")_. This will print the current user id  and the account id. 

That's why I want to set some values in the context in the middleware of faktory

**Comment by mperham** [comment]
The contents of the job hash are the only data you have so you want to plug your contextual data into the Custom hash before pushing it to Faktory.  When the worker process pulls the job, you can create a middleware which does something like this:

```go
func SetupContext(ctx Context, job *faktory.Job) error {
  aid := job.GetCustom("account_id")
  uid := job.GetCustom("user_id")
  // do something with them...
}

mgr.Use(SetupContext)
```

**Comment by mperham** [comment]
#38
