### ISSUE TITLE
Sending structs to jobs

### ISSUE THREAD

**Issue by adrianotadao** [contribsys/faktory_worker_go#37]
Hey Mike, sorry for bothering you too much.

I have a question, Is there a way of sending a `struct` to a job?

```go
import (
  faktory "github.com/contribsys/faktory/client"
)

type Potato struct {
  id string
  name string
}

potato := &Potato{"123", "Go potato!!"}

client, err := faktory.Open()
job := faktory.NewJob("SomeJob", potato)
err = client.Push(job)
```

I'm not sure if I have to use `job.SetCustom("potato", potato)` or not... If I have to do it, I don't know how to get potato from the job. 🤕 

thank you very much!

**Comment by mperham** [comment]
Job arguments must be basic JSON datatypes; you can't pass complex objects or structs. So you can do something like:

```
faktory.NewJob("SomeJob", potato_id, potato_name)
```

Or a map of simple types:

```
potatoMap := map[string]interface{}{ "id": potato.id, "name": potato.name, }
faktory.NewJob("SomeJob", potato_map)
```

As long as it serializes cleanly with `json.Marshal`, you should be good.

https://github.com/contribsys/faktory/wiki/The-Job-Payload

**Comment by adrianotadao** [comment]
Gotcha. Thank you very much @mperham.
