### ISSUE TITLE
testing/mocking pool connections and clients

### ISSUE THREAD

**Issue by kulkarnisameer7** [contribsys/faktory_worker_go#46]
I couldn't find any documentation on how to test/mock pool connections, getting a client from the pool, registering a mock handler, adding a new job etc. I am wondering what you think about this pattern, and if it makes sense:

```
	mgr := worker.NewManager()

	mgr.ProcessStrictPriorityQueues("fwgtest")

	mgr.Concurrency = 1

	pool, _ := faktory.NewPool(5)

	faktory.RandomProcessWid = mgr.ProcessWID

	mgr.Pool = pool

	mgr.Register("aworker", func(ctx context.Context, args ...interface{}) error {
		return nil
	})

	j := faktory.NewJob("something", 1, 2)

	perf := worker.NewTestExecutor(pool)

	err := perf.Execute(j, func(ctx context.Context, args ...interface{}) error {
		return nil
	})

	suite.NoError(err)

```

This doesn't work, I am just playing around and trying to figure out how to mock these guys. This is mainly for travis, and if mocking isn't possible I think I might have to install faktory and redis on the travis node.

**Comment by mperham** [comment]
I don't want to overload the readme with too much detail.  You are welcome to start a Testing wiki page.
