### ISSUE TITLE
Can't get a minimal working example

### ISSUE THREAD

**Issue by nflorentin** [contribsys/faktory_worker_go#53]
Hi,

I've successfully make faktory_worker_ruby working but I can't make it worked with go.

Faktory is installed and is running.

I copy and run the test/main.go in my project and it didn't work. So I clone this repo and tried to run test/main.go with no success.

I'm having the following error in both cases:
```bash
nicolas@mbp-nicolas faktory_worker_go % go run test/main.go
2021/01/19 18:01:35.217337 faktory_worker_go 1.4.0 PID 88049 now ready to process jobs
&{Pool:0xc000190220}
panic: Expected: <nil>

goroutine 6 [running]:
main.unique.func1(0xc0001922c0, 0xc0001922c0, 0x0)
	/Users/nicolas/www/others/faktory_worker_go/test/main.go:117 +0x359
github.com/contribsys/faktory/client.(*Pool).With(0xc00018a2b0, 0xc0001a7fa0, 0x0, 0x0)
	/Users/nicolas/go/pkg/mod/github.com/contribsys/faktory@v1.3.0-1/client/pool.go:54 +0x9f
main.unique()
	/Users/nicolas/www/others/faktory_worker_go/test/main.go:98 +0x127
main.main.func3(0xc00001c3f0)
	/Users/nicolas/www/others/faktory_worker_go/test/main.go:80 +0x38
created by main.main
	/Users/nicolas/www/others/faktory_worker_go/test/main.go:74 +0x6bb
exit status 2
```

Thanks in advance for your help

**Comment by mperham** [comment]
Test/main.go is part of the test suite, not meant to be used. Did you read thru the readme?

**Comment by nflorentin** [comment]
Hmm, the worst is that yes I read the readme.

I think the sentence "See test/main.go for a working example" made me think that the snippet of the readme was incomplete and that the file test/main.go was a more complete example.

So the snippet of the readme is "production ready" ?

**Comment by mperham** [comment]
Sorry for the confusion. test/main.go is meant to be working example code
but you will need to modify it for any use.

**Comment by nflorentin** [comment]
@mperham A big thank for your reactivity and your awesome work on Sidekiq and Faktory :)
