### ISSUE TITLE
Batch ID Inconsistency

### ISSUE THREAD

**Issue by kdebacker** [contribsys/faktory_worker_go#54]
There is an inconsistency between this repository and [contribsys/faktory](https://github.com/contribsys/faktory) in regards to the batch id. In this repository it expects `_bid` according to [this line in context.go](https://github.com/contribsys/faktory_worker_go/blob/master/context.go#L80), but in contribsys/faktory it only sets `bid` when you [push jobs to the batch](https://github.com/contribsys/faktory/blob/master/client/batch.go#L89).
I'm currently working around this by setting `_bid` manually, but I image this is not the intention since this is not added in the test/example file.

I'm not sure this is the correct repository to create this issue, but I figured it's a start.
I tried to look at the Ruby client implementation and it looks like that one is using `bid`, but the documentation states that custom metadata elements starting with '_' are reserved for internal use.

One additional note; It might be wise to include the batch mechanism in the specifications to avoid this type of inconsistencies in the future.

**Comment by mperham** [comment]
Yeah, that was changed in #49 and I don't know why it was broken for him. I should have dug deeper. You are right: "bid" is used for jobs within a batch. "_bid" is used for callback jobs to signify which batch they are part of but not "within".

**Comment by mperham** [comment]
09e2bf17cd784faf7015bda25b0af126ec021987
