### ISSUE TITLE
Test if a job is pushed to the client from within a worker

### ISSUE THREAD

**Issue by robinvdvleuten** [contribsys/faktory_worker_go#56]
I am currently using the `testing` package to test the worker's perform method. Within my worker's method, I am pushing new jobs to a different worker and I would like to assert if that is happening.

```go
myFunc := func(ctx context.Context, args ...interface{}) error {
	return help.With(func(cl *faktory.Client) error {
        job := faktory.NewJob("AnotherJob", 2)
        return cl.Push(job)
    })
}

pool, err := faktory.NewPool(5)
perf := worker.NewTestExecutor(pool)

somejob := faktory.NewJob("OneJob", 1)
err = perf.Execute(somejob, myFunc)

// assert if another job is pushed...
```

It would be really helpful to have such helper.

**Comment by mperham** [comment]
An integration test like that should be contacting Faktory directly and asserting on the size of the queues based on the results of the INFO command. Adding an API to do so on to of `github.com/contribsys/faktory/client` would be a nice PR.

**Comment by robinvdvleuten** [comment]
I can create a PR for that, no problem! But can you maybe then give a small example on how to retrieve the client from this test pool?

**Comment by mperham** [comment]
https://github.com/contribsys/faktory_worker_go/blob/14e11b56486971126291f040ac4d131ff00b9687/test/main.go#L98

**Comment by robinvdvleuten** [comment]
I've created a PR on Faktory (https://github.com/contribsys/faktory/pull/365)
