### ISSUE TITLE
Worker struct not updating between different unit tests

### ISSUE THREAD

**Issue by bschreck** [contribsys/faktory_worker_go#60]
I have a series of golang tests using a local pool with concurrency of 1. It seems that the worker state is leaking between unit tests nondeterministically, and I'm struggling to find in the docs or source code where this could be happening. We initialize a struct called Worker that contains a faktory_worker_go.Manager instance, and call worker.manager.Register(job_name, worker.JobFunc) for all of our job handlers. Inside the handlers, the reference to the worker struct sometimes does not contain variables from the current test, and instead contains old variables from previous tests. Any ideas why?

**Comment by mperham** [comment]
Show me the code.

**Comment by bschreck** [comment]
Ah I think I found the issue. I will close for now.

We had an integration test that was creating a real worker pool and sending the manager to the pool. When this was run alongside our other tests with fake workers, it was causing some tests to fail. I believe that the jobs in the other tests were being sent to the real pool.

Not adding code here (yet, unless we need to reopen in the future), because I would need to pair down to a minimum working example with sensitive info removed
