### ISSUE TITLE
ERR Job not found

### ISSUE THREAD

**Issue by bploetz** [contribsys/faktory_worker_go#66]
While looking in our faktory worker logs, the log was filled with these two log statements over and over again, printed every second:

```
2022/09/06 12:39:51.608495 ERR Job not found 148ec8b7-8417-45e9-bbc0-66f7a1a4d7e0
2022/09/06 12:39:51.608541 ERR Job not found 9e286640-ec97-47f2-9a49-d50c5e6ed0a2
2022/09/06 12:39:52.609932 ERR Job not found 148ec8b7-8417-45e9-bbc0-66f7a1a4d7e0
2022/09/06 12:39:52.610081 ERR Job not found 9e286640-ec97-47f2-9a49-d50c5e6ed0a2
2022/09/06 12:39:53.611083 ERR Job not found 9e286640-ec97-47f2-9a49-d50c5e6ed0a2
2022/09/06 12:39:53.611083 ERR Job not found 148ec8b7-8417-45e9-bbc0-66f7a1a4d7e0
2022/09/06 12:39:54.612050 ERR Job not found 148ec8b7-8417-45e9-bbc0-66f7a1a4d7e0
2022/09/06 12:39:54.612227 ERR Job not found 9e286640-ec97-47f2-9a49-d50c5e6ed0a2
2022/09/06 12:39:55.613489 ERR Job not found 148ec8b7-8417-45e9-bbc0-66f7a1a4d7e0
2022/09/06 12:39:55.613531 ERR Job not found 9e286640-ec97-47f2-9a49-d50c5e6ed0a2
........etc........
```

I searched for this error message in our code and did not find anything, so I assume this is coming from Faktory itself. What does this mean and how do I get it to stop spamming our logs?

**Comment by mperham** [comment]
Yeah, bad error message.

That message indicates that, when the worker sends FAIL for a JID, Faktory doesn't have a reservation record for that job. I know there have been bug fixes around that logic in previous versions but I don't know what version you are running.

**Comment by bploetz** [comment]
@mperham we're running faktory server 1.6.0 and faktory worker go 1.6.0

**Comment by mperham** [comment]
It looks like your worker process is trapped in this infinite loop, trying to report the result of executing a job which the server doesn't know about.

https://github.com/contribsys/faktory_worker_go/blob/3e4ff4092bfca045328c87b5357ad122856a1d37/runner.go#L163-L184

The most likely issue is that your jobs ran really long; their job reservations timed out and were garbage collected within Faktory. I think that infinite loop in the worker is a mistake. The worker should retry a few times but not forever.

**Comment by mperham** [comment]
Yep, restart the worker.

**Comment by bploetz** [comment]
Restarted the worker process and confirmed the log messages go away. Thanks @mperham.

**Comment by mperham** [comment]
Remove infinite loop, 77f76ae025051db0ef7c6a5a26366421e21592a9

**Comment by nqd** [comment]
@mperham are you going to release new version for this? Kind of annoying to manually check and restart the worker

**Comment by mperham** [comment]
Thanks for reminding me. I just tagged v1.6.1.
