### ISSUE TITLE
how to connect worker to a server (not localhost)

### ISSUE THREAD

**Issue by Zambiorix** [contribsys/faktory_worker_go#81]
Hello

My application is running in a separate docker container.
Both the faktory and my app container are added to the same docker network.
The hostname of my faktory container is "faktory"
I can ping the "faktory" from my app container, so they can see each other.

But how do I have my worker connect to the "faktory" hostname instead of localhost?
I do not see a way to configure this?

Thank you
Cheers
Gerd

**Comment by mperham** [comment]
You'd set the FAKTORY_URL environment variable for the worker process.

**Comment by Zambiorix** [comment]
For reference:
`
jobs.Pool, _ = Faktory.NewPoolWithDialer(services.jobs.Concurrency+2, &jobsDailer{Address: "faktory:7419"})
`

`
// jobsDailer
type jobsDailer struct{ Address string }

// Dial
func (jobsDailer *jobsDailer) Dial(network, addr string) (c net.Conn, err error) {

	return net.Dial(network, jobsDailer.Address)
}
`
