### ISSUE TITLE
Shutdown/Quiet events aren't fired

### ISSUE THREAD

**Issue by hassansin** [contribsys/faktory_worker_go#9]
Worker doesn't response to shutdown/quiet actions from the server. https://github.com/contribsys/faktory_worker_go/blob/master/runner.go#L140 . Here server is returning json response of `{"state":"quiet"}`, but the client is checking against plain text. Might need a json parsing. I can send a PR with the fix.

**Comment by mperham** [comment]
A PR would be very welcome!
